---
version: 3

tasks:
  build:
    desc: Build NixOS flakes
    cmds:
      - nixos-rebuild build --flake .#home

  diff:
    desc: Build & diff against the current system
    cmds:
      - task: build
      - nvd diff /run/current-system result

  install:
    desc: Install (update) the current system
    cmds:
      - sudo nixos-rebuild switch --flake .#home

  update:
    desc: Update Nix flakes
    cmds:
      - nix flake update
      - task: diff

  format:
    desc: Format Nix files
    cmds:
      - alejandra .

  check:
    desc: Check Nix flakes
    cmds:
      - nix flake check

  wsl:build:
    desc: Build NixOS home-manager config
    cmds:
      - nix run nixpkgs#home-manager -- build --flake .#wsl

  wsl:diff:
    desc: Build & diff against the current home-manager config
    cmds:
      - task: wsl:build
      - nvd diff ~/.local/state/home-manager/gcroots/current-home result

  wsl:install:
    desc: Install (update) the current home-manager config
    cmds:
      - nix run nixpkgs#home-manager -- switch --flake .#wsl
