---
version: 3

tasks:
  build:
    desc: Build NixOS flakes
    cmds:
      - nixos-rebuild build --flake .#home

  diff:
    desc: Build & diff against the current system
    cmds:
      - task: build
      - nvd diff /run/current-system result

  install:
    desc: Install (update) the current system
    cmds:
      - sudo nixos-rebuild switch --flake .#home

  update:
    desc: Update Nix flakes
    cmds:
      - nix flake update
      - task: install

  format:
    desc: Format Nix files
    cmds:
      - alejandra .

  check:
    desc: Check Nix flakes
    cmds:
      - nix flake check
