---
version: 3

vars:
  HOSTNAME_SHORT:
    sh: hostname -s | tr '[:upper:]' '[:lower:]'
  REBUILD_CMD:
    sh: |
      case "$(uname -s)" in
        Darwin) echo darwin-rebuild ;;
        Linux) echo nixos-rebuild ;;
        *) echo "Unsupported OS: $(uname -s)" >&2; exit 1 ;;
      esac

tasks:
  build:
    desc: Build NixOS flakes
    cmds:
      - '{{.REBUILD_CMD}} build --flake ".#{{.HOSTNAME_SHORT}}"'

  diff:
    desc: Build & diff against the current system
    cmds:
      - task: build
      - nvd diff /run/current-system result

  install:
    desc: Install (update) the current system
    cmds:
      - sops -d secrets/contact.yaml > /dev/null
      - 'sudo {{.REBUILD_CMD}} switch --flake ".#{{.HOSTNAME_SHORT}}"'

  update:
    desc: Update Nix flakes
    cmds:
      - nix flake update

  format:
    desc: Format Nix files
    cmds:
      - alejandra .

  check:
    desc: Check Nix flakes
    cmds:
      - nix flake check --all-systems
