{
  imports = [
    ./avahi.nix
    ./blueman.nix
    ./davfs2.nix
    ./dbus.nix
    ./gvfs.nix
    ./kubo.nix
    ./nginx.nix
    ./openssh.nix
    ./pipewire.nix
    ./printing.nix
    ./resolved.nix
    ./rpcbind.nix
    ./samba.nix
    ./tailscale.nix
    ./xserver.nix
  ];
}
