final: prev: let
  inherit (builtins) elemAt;

  github-tags = ["google-antigravity/antigravity-cli" "1.0.3"];
  version = elemAt github-tags 1;

  # Auto-generated by the overlay hash refresh workflow from release assets.
  source-url-aarch64-darwin = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.0.6/agy_cli_mac_arm64.tar.gz";
  source-url-aarch64-linux = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.0.6/agy_cli_linux_arm64.tar.gz";
  source-url-x86_64-darwin = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.0.6/agy_cli_mac_x64.tar.gz";
  source-url-x86_64-linux = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.0.6/agy_cli_linux_x64.tar.gz";

  hash-src-aarch64-darwin = "sha256-/l9FOjZD3GeCVKDb561SGdFGGdPe5bVv8LqUK6gXzy4=";
  hash-src-aarch64-linux = "sha256-15euZvrGWZoL5HYaNZyOSytfLut/9sCJ/mYs73ADgxE=";
  hash-src-x86_64-darwin = "sha256-h5mk5B+QTJXVddJtg4hPwBVmASSFuafI08CpbSvClVs=";
  hash-src-x86_64-linux = "sha256-NQ2IY87/uC5DyTDByZbir8yWY1T2bE7i5fu0XnatvUs=";
in {
  antigravity-cli = prev.antigravity-cli.overrideAttrs (old: let
    sources = prev.lib.mapAttrs (_: source: prev.fetchzip source) {
      x86_64-linux = {
        url = source-url-x86_64-linux;
        hash = hash-src-x86_64-linux;
      };
      aarch64-linux = {
        url = source-url-aarch64-linux;
        hash = hash-src-aarch64-linux;
      };
      aarch64-darwin = {
        url = source-url-aarch64-darwin;
        hash = hash-src-aarch64-darwin;
      };
      x86_64-darwin = {
        url = source-url-x86_64-darwin;
        hash = hash-src-x86_64-darwin;
      };
    };
  in {
    inherit version;
    src =
      sources.${prev.stdenv.hostPlatform.system}
      or (throw "Unsupported system: ${prev.stdenv.hostPlatform.system}");
    passthru = (old.passthru or {}) // {inherit sources;};
  });
}
