final: prev: let
  inherit (builtins) elemAt;

  github-tags = ["google-antigravity/antigravity-cli" "1.0.9"];
  version = elemAt github-tags 1;

  # Auto-generated by the overlay hash refresh workflow from release assets.
  source-url-aarch64-darwin = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.0.9/agy_cli_mac_arm64.tar.gz";
  source-url-aarch64-linux = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.0.9/agy_cli_linux_arm64.tar.gz";
  source-url-x86_64-darwin = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.0.9/agy_cli_mac_x64.tar.gz";
  source-url-x86_64-linux = "https://github.com/google-antigravity/antigravity-cli/releases/download/1.0.9/agy_cli_linux_x64.tar.gz";

  # Keep these as top-level `hash-*` variables (not inlined in `sources`):
  # `.github/workflows/renovate_overlay_hashes.yaml` parses and rewrites them.
  hash-src-aarch64-darwin = "sha256-foOBabJqQAu08M9WGBoZZ6M6QckKwrneWG0ARTn05gI=";
  hash-src-aarch64-linux = "sha256-lE1nBWt8xuRBHcqE2fB3seRgyM0qRDLSzfIZQh/3Plo=";
  hash-src-x86_64-darwin = "sha256-1mXzpNPDpXuMoXdCqyEm/6rdIawDHVfaL7u0klzddw0=";
  hash-src-x86_64-linux = "sha256-zYD4X0O1Kzide0mNZ4T4MW1Xqcxi6uI9hAxd42j5xNU=";
in {
  antigravity-cli = prev.antigravity-cli.overrideAttrs (old: let
    sources = prev.lib.mapAttrs (_: source: prev.fetchurl source) {
      x86_64-linux = {
        url = source-url-x86_64-linux;
        hash = hash-src-x86_64-linux;
      };
      aarch64-linux = {
        url = source-url-aarch64-linux;
        hash = hash-src-aarch64-linux;
      };
      aarch64-darwin = {
        url = source-url-aarch64-darwin;
        hash = hash-src-aarch64-darwin;
      };
      x86_64-darwin = {
        url = source-url-x86_64-darwin;
        hash = hash-src-x86_64-darwin;
      };
    };
  in {
    inherit version;
    src =
      sources.${prev.stdenv.hostPlatform.system}
      or (throw "Unsupported system: ${prev.stdenv.hostPlatform.system}");
    sourceRoot = ".";
    passthru = (old.passthru or {}) // {inherit sources;};
  });
}
