name: Nix

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    runs-on:
    - nscloud-ubuntu-22.04-amd64-2x4-with-cache
    - nscloud-cache-size-20gb
    - nscloud-git-mirror-5gb

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Lix
      uses: cachix/install-nix-action@v26
      with:
        install_url: https://install.lix.systems/lix
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes
    - name: Check Nix flake
      run: nix flake check
