name: Nix

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    runs-on:
    - nscloud-ubuntu-22.04-amd64-2x4-with-cache
    - nscloud-cache-size-20gb
    - nscloud-git-mirror-5gb

    steps:
    - name: Checkout
      uses: namespacelabs/nscloud-checkout-action@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        install_url: https://install.lix.systems/lix
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes
      env:
        NIX_INSTALLER_NO_CONFIRM: 1
        NIX_INSTALLER_ENABLE_FLAKES: 1

    - name: Check Nix flake
      run: nix flake check
